mqtt_bridge_node:
  ros__parameters:
    mqtt:
      client:
        protocol: 4      # MQTTv311
      connection:
        host: "mqtt.devwarp.work"
        port: 1883
        keepalive: 60
      private_path: "device/001"
    serializer: json:dumps
    deserializer: json:loads
    n_bridges: 8
    bridge:
      bridge1: ["mqtt_bridge.bridge:RosToMqttBridge","sensor_msgs.msg:NavSatFix","/fix","fix"]
      bridge2: ["mqtt_bridge.bridge:RosToMqttBridge","sensor_msgs.msg:Imu","/sensor/bwt901cl/Imu","Imu"]
      bridge3: ["mqtt_bridge.bridge:RosToMqttBridge","geometry_msgs.msg:Vector3","/sensor/bwt901cl/Angle","Angle"]
      bridge4: ["mqtt_bridge.bridge:RosToMqttBridge","sensor_msgs.msg:MagneticField","/sensor/bwt901cl/MagneticField","MagneticField"]
      bridge5: ["mqtt_bridge.bridge:RosToMqttBridge","std_msgs.msg:Int8","/kentora/BatteryLevel","BatteryLevel"]
      bridge6: ["mqtt_bridge.bridge:RosToMqttBridge","std_msgs.msg:Int16","/kentora/Rpm","Rpm"]
      bridge7: ["mqtt_bridge.bridge:RosToMqttBridge","std_msgs.msg:Int8","/kentora/EcuMode","EcuMode"]
      bridge8: ["mqtt_bridge.bridge:RosToMqttBridge","std_msgs.msg:Int16","/kentora/Steering","Steering"]


